import img from '../../img/ellipse.svg';
import imgDots from '../../img/decor.svg';
import imgDotsDark from '../../img/decorDark.svg';
import waves from '../../img/waves.svg';
import wavesDark from '../../img/wavesDark3.svg';

export const lightTheme = {
    body: '#fff',
    text: '#000000',
    headerBlockBg: `#FFFFFF url(${img}) no-repeat 589px center`,
    headerBlockShadow: '0px 5px 30px rgba(56, 56, 56, 0.25)',
    headerBlockEllipseBg: '#C4C4C4',
    headerBlockEllipseBigBg: '#F23F3F',
    headerBlockDecor: `url(${imgDots}) no-repeat center center`,
    headerLogoOneDisplay: 'block',
    headerLogoTwoDisplay: 'none',
    headerLogoTwoFilter: 'drop-shadow(0px 4px 4px rgba(0, 0, 0, 0.25))',
    headerLogoThreeDisplay: 'none',
    headerNavColor: '#383838',
    headerNavFontWeight: '600',
    headerNavbarBg: '#F23F3F',
    headerNavbarShadow: 'none',
    headerNavActiveBg: '#ffffff',
    headerNavActiveShadow: '0px 5px 30px rgba(56, 56, 56, 0.25)',
    headerBtn: '#F23F3F',
    headerBtnShadow: '0px 5px 15px rgba(56, 56, 56, 0.4)',
    headerBtnHoverShadow: '0px 4px 8px rgba(56, 56, 56, 0.4)',
    headerTwoNavBg: '#F23F3F',
    headerTwoNavShadow: '0px 5px 30px rgba(56, 56, 56, 0.25)',
    toggleCircleBg: '#AAAAAA',
    toggleCircleWeight: '500',
    widgetsBg: '#36C858',
    widgetsShadow: '0px 4px 8px rgba(0, 0, 0, 0.25)',
    widgetsBorder: '1px solid #36C858',
    widgetsHoverBg: '#2ca548',
    widgetsImgOpacity: '1',
    homeBorder: `url(${waves}) repeat-x center top / contain`,
    directionsBg: '#F1F1F1',
    directionsShadow: 'inset 0 20px 20px -20px rgba(0, 0, 0, 0.23), inset 0 -20px 20px -20px rgba(0, 0, 0, 0.23)',
    directionsPageBg: '#ffffff',
    directionsPageShadow: 'none',
    directionsGeometricFigure: 'block',
    directionsGeometricFigureDark: 'none',
    directionsBtn: '#ffffff',
    directionsLinkTestColor: '#383838',
    directionsLinkTestWeight: '600',
    contactsBlockBg: '#ffffff',
    contactsBlockShadow: '0px 5px 30px rgba(0, 0, 0, 0.25)',
    contactsBlockColor: '#000000',
    footerBg: '#F23F3F',
    itKidsBlockBg: '#EAEAEA',
    trainingProgramBlockBg: '#EAEAEA',
    diplomaSpanColor: '#383838',
    priceWebDevCardBg: '#ffffff',
    priceWebDevAcceleratedImg: 'block',
    priceWebDevAcceleratedImgDark: 'none',
}

export const darkTheme = {
    body: '#3c3d42',
    text: '#fdfdfd',
    headerBlockBg: `#57595f`,
    headerBlockShadow: '0px 5px 30px rgba(0, 0, 0, 0.25)',
    headerBlockEllipseBg: '#7a7c7f',
    headerBlockEllipseBigBg: '#da3838',
    headerBlockDecor: `url(${imgDotsDark}) no-repeat center center`,
    headerLogoOneDisplay: 'none',
    headerLogoTwoDisplay: 'block',
    headerLogoTwoFilter: 'none',
    headerLogoThreeDisplay: 'none',
    headerNavColor: '#fdfdfd',
    headerNavFontWeight: '500',
    headerNavbarBg: '#515358',
    headerNavbarShadow: '0px 5px 15px rgba(0, 0, 0, 0.3)',
    headerNavActiveBg: '#515358',
    headerNavActiveShadow: '0px 5px 30px rgba(0, 0, 0, 0.3)',
    headerBtn: '#da3838',
    headerBtnShadow: '0px 5px 15px rgba(0, 0, 0, 0.3)',
    headerBtnHoverShadow: '0px 4px 8px rgba(0, 0, 0, 0.3)',
    headerTwoNavBg: '#515358',
    headerTwoNavShadow: '0px 5px 30px rgba(0, 0, 0, 0.3)',
    toggleCircleBg: '#7a7c7f',
    toggleCircleWeight: '400',
    widgetsBg: '#2ca548',
    widgetsShadow: '0px 4px 8px rgba(0, 0, 0, 0.5)',
    widgetsBorder: '1px solid #2ca548',
    widgetsHoverBg: '#2b8c41',
    widgetsImgOpacity: '0.9',
    homeBorder: `url(${wavesDark}) repeat-x center top / contain`,
    directionsBg: '#2c2d31',
    directionsShadow: 'inset 0 20px 20px -20px rgba(0, 0, 0, 0.4), inset 0 -20px 20px -20px rgba(0, 0, 0, 0.4)',
    directionsPageBg: '#3c3d42',
    directionsPageShadow: 'none',
    directionsGeometricFigure: 'none',
    directionsGeometricFigureDark: 'block',
    directionsBtn: '#ffffff',
    directionsLinkTestColor: '#e4e4e4',
    directionsLinkTestWeight: '500',
    contactsBlockBg: '#57595f',
    contactsBlockShadow: '0px 5px 30px rgba(0, 0, 0, 0.5)',
    contactsBlockColor: '#fdfdfd',
    footerBg: '#515358',
    itKidsBlockBg: '#5b5d63',
    trainingProgramBlockBg: '#5b5d63',
    diplomaSpanColor: '#a7a7a7',
    priceWebDevCardBg: '#5b5d63',
    priceWebDevAcceleratedImg: 'none',
    priceWebDevAcceleratedImgDark: 'block',
}